---
apiVersion: v1
kind: List
items:
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Tier1Gateway
    metadata:
      name: trusted-landing
      namespace: lob-app02
    spec:
      kubeSpec:
        service:
          type: LoadBalancer