---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: lob-app02-provider-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
    spec:
      displayName: lob-app02-provider-ws
      namespaceSelector:
        names:
        - eks-bk-lts-us-east-1-0/lob-app02
      privileged: false
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: lob-app02-provider-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: lob-app02-provider-ws
    spec:
      configMode: BRIDGED
      displayName: lob-app02-provider-gg
      namespaceSelector:
        names:
        - eks-bk-lts-us-east-1-0/lob-app02
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Tier1Gateway
    metadata:
      name: lob-app02-provider-t1
      namespace: lob-app02
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Tier1Gateway
    metadata:
      name: lob-app02-int-t1
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/gatewayGroup: lob-app02-provider-gg
        tsb.tetrate.io/workspace: lob-app02-provider-ws
    spec:
      workloadSelector:
        namespace: lob-app02
        labels:
          app: lob-app02-provider-t1
      internalServers:
      - hostname: internal-api-httpbin.gcp.cx.tetrate.info
        name: lob-app02-provider
        clusters:
        - name: eks-bk-lts-us-east-2-1
          weight: 100
